import localFont from "next/font/local";
import "./globals.css";

const geomanistRegular = localFont({
  src: "./fonts/Geomanist-Regular.woff2",
  variable: "--font-geomanist-regular",
  display: "swap",
});

const geomanistBook = localFont({
  src: "./fonts/Geomanist-Book.woff2",
  variable: "--font-geomanist-book",
  display: "swap",
});

const geomanistMedium = localFont({
  src: "./fonts/Geomanist-Medium.woff2",
  variable: "--font-geomanist-medium",
  display: "swap",
});

const geomanistBold = localFont({
  src: "./fonts/Geomanist-Bold.woff2",
  variable: "--font-geomanist-bold",
  display: "swap",
});

export const metadata = {
  title: "Mi Cuenta Infonavit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geomanistRegular.variable} ${geomanistBook.variable} ${geomanistMedium.variable} ${geomanistBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
